Allow specifying CA cert paths
ellexus/mistral_plugins pull request #111
Opened 2021-03-02 10:28 UTC by liamellexus

Fixes #110 

- [x] Development complete
- [ ] Documentation complete
- [ ] Test case added
- [x] Version number updated
- [x] Representative testing complete
- [ ] Full testing complete

2021-03-02 17:49 UTC, nick-ellexus requested changes
Fix the options/usage. Apart from that this looks fine.

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_elasticsearch/mistral_elasticsearch.c
> +                "  -f certificate_directory\n"
-f or -d ?

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_elasticsearch/mistral_elasticsearch.c
> +                     "[-c certificate_path] [-d certificate_directory]\n", name);
-d or -f?

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_elasticsearch/mistral_elasticsearch.c
> +        {"cert-dir", required_argument, NULL, 'f'},
aha, it is -f.

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_elasticsearch/mistral_elasticsearch.c
>          {"date", no_argument, NULL, 'd'},
let's either take this out or add it to the usage message.

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_influxdb/mistral_influxdb.c
> +             "[-c certificate_path] [-d certificate_directory]\n", name);
-f not -d

2021-03-02 17:49 UTC, nick-ellexus commented on output/mistral_splunk/mistral_splunk.c
> +        {"cert-dir", required_argument, NULL, 'd'},
best to use the same short code in all the plugins. Otherwise we're bound to get confused somewhere down the line.

2021-03-02 20:33 UTC, nick-ellexus requested changes
Better! Let's make them all consistent with -k?

2021-03-02 20:33 UTC, nick-ellexus commented on output/mistral_influxdb/readme.rst
> +  Disbale SSL certificate validation when connecting to InfluxDB.
*Disable

2021-03-02 20:33 UTC, nick-ellexus commented on output/mistral_influxdb/mistral_influxdb.c
> +        "  %s [-d database] [-h host] [-P port] [-e file] [-m octal-mode] [-u user] [-p password] [-s] [-v var-name ...]\n"
This summary omits the -k (skip SSL). Speaking of which, do we have that in the other plugins?

2021-03-02 20:33 UTC, nick-ellexus commented on output/mistral_influxdb/readme.rst
> +  The directory that contains the CA certificate(s) used to sign the certificate of the
Probably something here to make clear that you don't need both cert-path and cert-dir

2021-03-03 08:47 UTC, RichardSJordan approved these changes
A couple of typos, but otherwise looks good.

2021-03-03 08:47 UTC, RichardSJordan commented on output/mistral_elasticsearch/readme.rst
> +  Disbale SSL certificate validation when connecting to Elasticsearch.
Typo "Disbale" should be "Disable"

2021-03-03 08:47 UTC, RichardSJordan commented on output/mistral_splunk/readme.rst
> +  Disbale SSL certificate validation when connecting to Splunk.
Another instance of typo: "Disbale" should be "Disable"

2021-03-03 09:40 UTC, nick-ellexus approved these changes
Oh all right then.

2021-03-03 10:00 UTC, merged